AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bastion host para teste do ambiente'
Parameters:
  NetworkStackName:
    Type: String
    Description: Nome da stack de rede ja criada
    Default : NetworkStack
    
  KeyName:
    Description: EC2 KeyPair
    Type: List<AWS::EC2::KeyPair::KeyName>
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: O Range de IP que ira conectar no EC2
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSInstanceType2Arch:
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    t2.large:
      Arch: HVM64
  AWSInstanceType2NATArch:
    t2.nano:
      Arch: NATHVM64
    t2.micro:
      Arch: NATHVM64
    t2.small:
      Arch: NATHVM64
    t2.medium:
      Arch: NATHVM64
    t2.large:
      Arch: NATHVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0fc61db8544a617ed
    us-west-2:
      HVM64: ami-0ce21b51cb31a48b8
    us-west-1:
      HVM64: ami-09a7fe78668f1e2c0
    eu-west-1:
      HVM64: ami-04d5cc9b88f9d1d39
    eu-west-2:
      HVM64: ami-0cb790308f7591fa6
    eu-central-1:
      HVM64: ami-0ec1ba09723e5bfac
    ap-northeast-1:
      HVM64: ami-052652af12b58691f
    ap-northeast-2:
      HVM64: ami-0db78afd3d150fc18
    ap-southeast-1:
      HVM64: ami-0cbc6aae997c6538a
    ap-southeast-2:
      HVM64: ami-08fdde86b93accf1c
    ap-south-1:
      HVM64: ami-03b5297d565ef30a6
    us-east-2:
      HVM64: ami-0e01ce4ee18447327
    ca-central-1:
      HVM64: ami-0bf54ac1b628cf143
    sa-east-1:
      HVM64: ami-0b032e878a66c3b68
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      SubnetId: {'Fn::ImportValue': !Sub '${NetworkStackName}-PAZ1'}
      KeyName:
        Ref: KeyName
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - PublicIp